# Generated by Django 4.2 on 2025-07-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eloq_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='podcast',
            name='related_goals',
            field=models.ManyToManyField(related_name='podcasts', to='Eloq_app.interestprofile'),
        ),
        migrations.AlterField(
            model_name='video',
            name='related_goals',
            field=models.ManyToManyField(related_name='videos', to='Eloq_app.interestprofile'),
        ),
        migrations.AlterField(
            model_name='interestprofile',
            name='interests',
            field=models.ManyToManyField(related_name='interest_profiles', to='Eloq_app.interest'),
        ),
    ]
